# Generated by Django 2.2.4 on 2019-08-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('password', models.CharField(default='', max_length=500)),
                ('confirm_password', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
