# Generated by Django 2.2.4 on 2019-08-21 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0002_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
